services:
  - type: web
    name: roblox-data-server
    env: docker
    plan: free
    branch: main
    buildCommand: javac Server.java
    startCommand: java Server
    envVars:
      - key: PORT
        value: 8080
